name: Release Package

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    
    permissions: write-all

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          server-id: forgerock-private-releases
          server-username: FORGEROCK_MVN_USER
          server-password: FORGEROCK_MVN_PASS

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots --fail-at-end verify
        env:
          # These are taken from the settings.xml ForgeRock generates for you.
          # See the README for info on generating that file -- then grab the user/pass
          # and update it in settings -> secrets -> repository secrets.
          FORGEROCK_MVN_USER: ${{ secrets.FORGEROCK_MVN_USER }}
          FORGEROCK_MVN_PASS: ${{ secrets.FORGEROCK_MVN_PASS }}

      - uses: ncipollo/release-action@v1.12.0
        with:
          artifacts: "target/duo-universal-prompt-auth-node-*.jar"
          omitBody: true
          token: ${{ secrets.GITHUB_TOKEN }}
